#!/usr/bin/env php
<?php
/**
 * nanodcm file
 *
 * @package    Nanodicom
 * @category   Base
 * @author     Nano Documet <nanodocumet@gmail.com>
 * @version	   1.3.1
 * @copyright  (c) 2010-2011
 * @license    http://www.opensource.org/licenses/mit-license.php MIT-license
 */

/**
 * The Command Line interface for Nanodicom.
 *
 * This cli script helps you run Nanodicom from the command line without the need to create php files.
 * WARNING: Tested in Linux only.
 *
 * Heavily inspired by Goyote's Kohana Installer
 * [https://github.com/goyote/kohana-installer]
 *
 * @package    Nanodicom
 * @category   Cli
 * @author     Nano Documet <nanodocumet@gmail.com>
 * @version	   1.3.1
 * @copyright  (c) 2010-2011
 * @license    http://www.opensource.org/licenses/mit-license.php MIT-license
 * @license    http://kohanaframework.org/license
 */

class Nanodcm extends \Nanodicom\CLI\CLI
{
}

set_time_limit(0);

// First index is the name of this script
array_shift($argv);

$helper = new Nanodcm($argv);

if (empty($argv) OR $helper->has_option('verbose'))
{
	$helper->execute_help();
}
else if (method_exists($helper, $method = 'execute_'.strtolower(str_replace('-', '_', $argv[0]))))
{
	require_once 'nanodicom.php';
	call_user_func(array($helper, $method));
}
else if ( ! empty($argv[0]))
{
	exit("\"{$argv[0]}\" is not a valid command!\n\n");
}
